### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by xuer0902** [Lushenggang/laboratory#4]
您好，请问一下，我在使用您写的这个高亮插件的时候，当content内容过多的时候，搜索关键词，浏览器会出现卡死的现象，请问这个如何解决

**Comment by wintc23** [comment]
你好 可以看一下代码怎么写的吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lushenggang/laboratory"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月20日(星期五) 下午3:10
收件人:&nbsp;"Lushenggang/laboratory"<laboratory@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Lushenggang/laboratory] 请教一个问题 (#4)





 
您好，请问一下，我在使用您写的这个高亮插件的时候，当content内容过多的时候，搜索关键词，浏览器会出现卡死的现象，请问这个如何解决
